name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret_access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy and run some code
      env:
        DIR_PATH: /var/www/${{ secrets.MAIN_AWS_EC2_PORTFOLIO_DIR }}
      run: |
        aws ssm send-command \
            --instance-ids "${{ secrets.INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo cd $DIR_PATH", "git pull", "sudo chmod -R $USER:$USER $DIR_PATH", "npm run build", "php artisan cache:clear", "sudo chmod -R www-data:www-data storage", "sudo chmod -R www-data:www-data bootstrap/cache"]' \
            --comment "Deploying application code"
