name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MAIN_AWS_EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: ssh into instance and run code
      env:
        DIR_PATH: /var/www/${{ secrets.MAIN_AWS_EC2_PORTFOLIO_DIR }}
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.MAIN_AWS_EC2_USER }}@${{ secrets.MAIN_AWS_EC2_IP }} << 'EOF'
          sudo cd $DIR_PATH
          git pull
          sudo chmod -R $USER:$USER $DIR_PATH
          npm run build
          php artisan cache:clear
          sudo chmod -R www-data:www-data storage
          sudo chmod -R www-data:www-data bootstrap/cache
        EOF
      
