name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.MAIN_AWS_EC2_KEY }}

    - name: Copy files to repo directory
      env:
        DIR_PATH: /var/www/${{ secrets.MAIN_AWS_EC2_PORTFOLIO_DIR }}
      run: |
        scp -r ./ ${{ secrets.MAIN_AWS_EC2_USER }}@${{ secrets.MAIN_AWS_EC2_IP }}:/$DIR_PATH

    - name: ssh into instance and run code
      env:
        DIR_PATH: /var/www/${{ secrets.MAIN_AWS_EC2_PORTFOLIO_DIR }}
      run: |
        ssh ${{ secrets.MAIN_AWS_EC2_USER }}@${{ secrets.MAIN_AWS_EC2_IP }} << 'EOF'
          cd $DIR_PATH
          npm run build
          php artisan cache:clear
        EOF
      
