name: Deploy to EC2

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy and run some code
      run: |
        aws ssm send-command \
            --instance-ids "i-0ceef8e041cbec9af" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo -u ubuntu bash -c \"cd /var/www/robertamoah && git pull && /run/user/1000/fnm_multishells/336033_1726136558506/bin/npm run build && php artisan cache:clear && sudo service nginx restart \""]' \
            --comment "Deploying application code"
